---

collections:
  - name: "git@github.com:phenixid/ansible-pas.git#/phenixid/digo"
    type: git
    version: "v2.4.0"
  - name: "git@github.com:phenixid/ansible-pas.git#/phenixid/pas"
    type: git
    version: "v2.4.0"
