---

- hosts: digo
  vars:
    - digo_service_group: "{{ group }}"
    - digo_service_user: "{{ user }}"
    - digo_db_url: "{{ db_url }}"
    - digo_signing_service_url: "{{ signing_service_url }}"
    - digo_file_service_url: "{{ file_service_url }}"
    - digo_file_service_username: "{{ pas_admin_user }}"
    - digo_file_service_password: "{{ pas_admin_password }}"
  vars_files:
    - "vars.yml"
  roles:
    - phenixid.digo.systemd

