---

- hosts: sign
  vars:

    - user: "ec2-user"
    - source: {  type: "installer", local_path: "~/phxid_server_linux_x64_3_2_0.sh", remote_path: "/tmp" }
    - encryption_key: "<secret>"
    - admin_password: "<secret>"
    - license_file: "~/license.p12"
    - license_password: "<secret>"

    - hazelcast_password: "<secret>"
    - hazelcast_interface: "{{ inventory_hostname }}"
    - hazelcast_members: "{{ groups['sign'] | reject('search', inventory_hostname) }}"
    - config_api_host: "{{ inventory_hostname }}"
    - config_api_port: 9443
    - java_heap_size: "1536M"
    - pas_home: "/opt/phenixid/pas"

  pre_tasks:
    - name: "upload {{ source.local_path }}"
      copy:
        src: "{{ source.local_path }}"
        dest: "{{ source.remote_path }}/"
        mode: 0700
        force: yes
        owner: "{{ user }}"
    - name: "Stop pas service"
      systemd:
        state: stopped
        name: pas
      become: yes
      ignore_errors: yes
  post_tasks:
    - name: "Start pas service"
      systemd:
        state: restarted
        daemon_reload: yes
        name: pas
      become: yes
  roles:
    - phenixid.pas.pas


- hosts: sign
  vars:

    - idp_id: "idp.phenixid.se"
    - idp_metadata: "idp.xml"
    - sp_id: "spsign.dev.digo"
    - sp_metadata: "sp.sign.xml"
    - allowed_logout_target: ".*localhost.*|.*127.0.0.1.*|.*digo.example.org.*"
    - jwt_certificate: "cert.crt"
    - ca_keystore: "cert.p12"
    - ca_keystore_password: "cCqtZmgH4WTCF2U5"
    - subject_key_parameter: "CN={{ '{{item.givenName}}' }} {{ '{{item.sn}}' }} ({{ '{{item.mail}}' }}),dc=ad,dc=example,dc=org"

    - public_port: "80"
    - private_port: "8444"
    - config_api_host: "{{ inventory_hostname }}"
    - config_api_port: "9443"
    - config_api_url: "http://{{ config_api_host }}:{{ config_api_port }}"
    - certificate_directory: "/opt/phenixid/certs"
  pre_tasks:
    - name: "Waiting for config API to become available..."
      wait_for:
        host: "{{ config_api_host }}"
        port: "{{ config_api_port }}"
      delegate_to: 127.0.0.1
  post_tasks:
    - name: "Trigger STORE_UPDATED event"
      uri:
        method: POST
        url: "{{ config_api_url }}/state"
        body_format: json
      delegate_to: 127.0.0.1
  roles:
    - phenixid.pas.pas_ca
    - phenixid.pas.pas_sp
    - phenixid.pas.pas_federated_signing
