---
# defaults file for signing_service

signing_service_sp_force_authn: yes
pas_fedsign_jwt_attributes: signing_service_jwt_attributes | default(["id", "failURL", "successURL", "cancelURL"])
pas_http_allowed_logout_target: ".*{{ signing_service_client_url }}.*|.*{{ signing_service_url }}.*"
