---

- name: "Add install directory"
  file:
    path: "/opt/phenixid"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
    state: directory
  become: yes

- name: "Add certificate directory"
  file:
    path: "/opt/phenixid/certs"
    owner: "{{ user }}"
    mode: 0700
    state: directory
  become: yes

- name: "Upload {{ digo_installer.local_path }} to {{ digo_installer.remote_path }}"
  copy:
    src: "{{ digo_installer.local_path }}"
    dest: "{{ digo_installer.remote_path }}/"
    mode: 0700
    force: yes
    owner: "{{ user }}"
  become: yes

- include_role:
    name: phenixid.util.systemd
  vars:
    service_name: digo

- include_role:
    name: phenixid.digo.digo

- name: "Start service"
  systemd:
    state: started
    daemon_reload: yes
    name: digo
  become: yes
