---

- name: "Upload {{ digo_installer.local_path }} to {{ digo_installer.remote_path }}"
  copy:
    src: "{{ digo_installer.local_path }}"
    dest: "{{ digo_installer.remote_path }}/"
    mode: 0700
    force: yes
    owner: "{{ user }}"
  become: yes

- name: "Remove directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ digo_home }}/config"
    - "{{ digo_home }}/lib"
    - "{{ digo_home }}/public"
    - "{{ digo_home }}/resources"
  become: yes

- name: "Create directories and permissions for user {{ user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    recurse: yes
  with_items:
    - "{{ digo_home }}"
    - "{{ digo_home }}/config"
    - "{{ digo_home }}/logs"
  become: yes

- name: "Install from zip file {{ digo_installer.remote_path }}/{{ source.local_path | basename }}"
  unarchive:
    remote_src: yes
    src: "{{ digo_installer.remote_path }}/{{ digo_installer.local_path | basename }}"
    dest: "{{ digo_home }}"
    owner: "{{ user }}"
  become: yes

- name: "Add keys"
  copy:
    src: "{{ item.local_path }}"
    dest: "{{ item.remote_path }}/{{ item.local_path | basename }}"
    mode: 0400
    owner: "{{ user }}"
  with_items:
    - "{{ digo_saml_trust }}"
    - "{{ digo_jwt_private_key }}"
    - "{{ digo_jwt_public_key }}"
  become: yes

- name: "Add log configuration"
  copy:
    src: "{{ digo_log4j2_config_file }}"
    dest: "{{ digo_home }}/config/log4j2.xml"
    owner: "{{ user }}"
  become: yes
  when: digo_log4j2_config_file is defined

- name: "Add hazelcast configuration"
  copy:
    src: "{{ digo_hazelcast_config_file }}"
    dest: "{{ digo_home }}/config/hazelcast.xml"
    owner: "{{ user }}"
  become: yes
  when: digo_hazelcast_config_file is defined

- name: "Render config.json"
  template:
    src: "config.json.j2"
    dest: "{{ digo_home }}/config/config.json"
    mode: 0400
    owner: "{{ user }}"
  become: yes

- name: "Render start.sh"
  template:
    src: "start.sh.j2"
    dest: "{{ digo_home }}/start.sh"
    owner: "{{ user }}"
  become: yes

