---

- name: "Add http_configurations"
  uri:
    method: PUT
    url: "{{ pas_config_api_url }}/config/http_configurations"
    body: "{{ lookup('template', 'http_configurations.json.j2') }}"
    body_format: json
