---


# install pas
user: "phxid"
group: "phxid"
pas_home: "/opt/phenixid/pas"
pas_installer: {  type: "installer", local_path: "/path/to/phxid_server_linux_x64_3_2_0.sh", remote_path: "/home/{{ user }}" }
pas_license_file: "/path/to/license.p12"
pas_start_script: "start-PhenixID.sh"
pas_enc_key: "<secret>"
pas_admin_user: "phxid"
pas_admin_password: "<secret>"
pas_license_password: "<secret>"
pas_session_cluster_password: "<secret>"
pas_session_cluster_interface: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"
pas_session_cluster_members: "{{ groups['sign'] | reject('search', inventory_hostname) | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | list }}"
pas_config_api_host: "{{ inventory_hostname }}"
pas_config_api_port: 9443
pas_config_api_url: "http://{{ pas_config_api_host }}:{{ pas_config_api_port }}"

# configure signing service
signing_service_client_url: "{{ digo_service_url }}"
signing_service_idp_metadata: "idp.xml"
signing_service_idp_id: "idp.phenixid.se"
signing_service_sp_id: "spsign.dev.digo"
signing_service_jwt_certificate: { local_path: "/path/to/jwt.crt", remote_path: "/opt/phenixid/certs" }
signing_service_ca_keystore: "/path/to/ca.p12"
signing_service_ca_keystore_password: "cCqtZmgH4WTCF2U5"
signing_service_ca_keystore_alias: "0"
signing_service_subject_key_properties: ["cn", "sn", "mail"]
signing_service_subject_key: "CN={{ '{{item.cn}}' }} {{ '{{item.sn}}' }} ({{ '{{item.mail}}' }}),dc=ad,dc=example,dc=org"

signing_service_ca_profiles: "pas_ca_profiles.json.j2"

signing_service_public_port: "8080"
signing_service_private_port: "8444"

# install and configure digo
digo_install_directory: "/opt/phenixid"
digo_installer: {  type: "installer", local_path: "/path/to/digo-phenixid-0.59-lib.tar.gz", remote_path: "/home/{{ user }}" }
digo_public_port: 8080

digo_file_location_id: 1
digo_file_location_path: "/opt/files"

digo_smtp_host: "smtp.sendgrid.net"
digo_smtp_port: "587"
digo_smtp_trust: "smtp.mailtrap.io"
digo_smtp_from: "digo@example.org"
digo_smtp_enabled: false
digo_smtp_username: "apikey"
digo_smtp_password: "<token>"
digo_smtp_auth_enabled: false

digo_db_user: "sa"
digo_db_password: "<secret>"

digo_sp_id: "spauthn.dev.digo"
digo_saml_trust: { local_path: "digo-saml-trust.pem", remote_path: "/opt/phenixid/certs"}
digo_jwt_private_key: { local_path: "key.der", remote_path: "/opt/phenixid/certs" }
digo_jwt_public_key: { local_path: "public-key.der", remote_path: "/opt/phenixid/certs" }

digo_saml_idp_id: "{{ pas_sp_idp_id }}"
digo_saml_authority: "description"
digo_saml_source: "source"
digo_saml_first_name: "cn"
digo_saml_last_name: "sn"
digo_saml_mail: "mail"

digo_employee_organization: "o"
digo_employee_user_id: "uid"
digo_employee_mail: "mail"
digo_employee_first_name: "cn"
digo_employee_last_name: "sn"
digo_employee_mobile: "mobile"
digo_employee_department: "ou"

digo_citizen_info: "o"
digo_citizen_mail: "mail"
digo_citizen_mobile: "mobile"
digo_citizen_first_name: "cn"
digo_citizen_last_name: "sn"
