---

- name: "Add system group {{ digo_service_group }}"
  group:
    name: "{{ digo_service_group }}"
    system: yes
    state: present
  become: true

- name: "Add system user {{ digo_service_user }}"
  user:
    name: "{{ digo_service_user }}"
    groups: "{{ digo_service_group }}"
    append: no
    system: yes
    state: present
  become: true

- name: "Upload {{ digo_installer.local_path }} to {{ digo_installer.remote_path }}"
  copy:
    src: "{{ digo_installer.local_path }}"
    dest: "{{ digo_installer.remote_path }}/"
    mode: 0400
    force: yes
    owner: "{{ digo_service_user }}"
  when: digo_installer.remote_path is not undefined
  become: yes

- include_role:
    name: phenixid.digo.digo
