---

- name: "Waiting for config API to become available..."
  wait_for:
    host: "{{ pas_config_api_host }}"
    port: "{{ pas_config_api_port }}"
  when: skip_configure|default(False) == False

- name: "Configure federated signing"
  include_role:
    name: phenixid.pas.pas_fedsign
  when: skip_configure|default(False) == False

- name: "Trigger STORE_UPDATED event"
  uri:
    method: POST
    url: "{{ pas_config_api_url }}/state"
    body_format: json
  when: skip_configure|default(False) == False
