---

- include_role:
    name: phenixid.util.systemd
  vars:
    service_name: pas
  when: skip_install|default(False) == False

- include_role:
    name: phenixid.pas.pas
  when: skip_install|default(False) == False

- name: "Start service"
  systemd:
    state: started
    daemon_reload: yes
    name: pas
  become: yes
  when: skip_install|default(False) == False

- name: "Waiting for config API to become available..."
  wait_for:
    host: "{{ pas_config_api_host }}"
    port: "{{ pas_config_api_port }}"
  when: skip_configure|default(False) == False

- include_role:
    name: phenixid.pas.pas_fedsign
  when: skip_configure|default(False) == False

- name: "Trigger STORE_UPDATED event"
  uri:
    method: POST
    url: "{{ pas_config_api_url }}/state"
    body_format: json
  when: skip_configure|default(False) == False
