---

- name: "Create certificate directory"
  file:
    path: "{{ pas_fedsign_jwt_certificate.remote_path }}"
    state: directory
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
    mode: 0500
  become: yes

- name: "Add certificate for jwt validation"
  copy:
    src: "{{ pas_fedsign_jwt_certificate.local_path }}"
    dest: "{{ pas_fedsign_jwt_certificate.remote_path }}/{{ pas_fedsign_jwt_certificate.local_path | basename }}"
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
    mode: 0400
  become: yes

- name: "Waiting for config API to become available..."
  wait_for:
    host: "{{ pas_config_api_host }}"
    port: "{{ pas_config_api_port }}"
  when: skip_configure|default(False) == False

- name: "Configure federated signing"
  include_role:
    name: phenixid.pas.pas_fedsign
  when: skip_configure|default(False) == False

- name: "Trigger STORE_UPDATED event"
  uri:
    method: POST
    url: "{{ pas_config_api_url }}/state"
    body_format: json
  when: skip_configure|default(False) == False
