---

- name: "Remove directories"
  file:
    path: "{{ pas_home }}/{{ item }}"
    state: absent
    owner: ec2-user
  with_items:
    - "bin"
    - "classes"
    - "config"
    - "data"
    - "jre"
    - "lib"
    - "license"
    - "mods"
    - "repo"
    - "repos.txt"
    - "resources"
    - "tokensin"
    - "tokensout"
    - "uninstall"

- name: "Create install directory {{ pas_home }}"
  file:
    path: "{{ pas_home }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
  with_items:
    - "license"
    - "config"
  become: yes

- name: "Render install.varfile"
  template:
    src: install.varfile.j2
    dest: "{{ pas_home }}/install.varfile"
    owner: "{{ user }}"

- name: "Install from installer {{ source.local_path | basename }}"
  command: "{{ source.remote_path }}/{{ source.local_path | basename }} -q -varfile {{ pas_home }}/install.varfile"
  when: source.type == "installer"

- name: "Install from zip {{ source.local_path | basename }}"
  unarchive:
    remote_src: yes
    src: "{{ source.remote_path }}/{{ source.local_path | basename }}"
    dest: "{{ pas_home }}"
    owner: "{{ user }}"
  when: source.type == "zip"

- name: "Render sessions.xml"
  template:
    src: sessions.xml.j2
    dest: "{{ pas_home }}/config/sessions.xml"
    owner: "{{ user }}"

- name: "Render boot.json"
  template:
    src: boot.json.j2
    dest: "{{ pas_home }}/config/boot.json"
    owner: "{{ user }}"

- name: "Add start script"
  copy:
    src: "{{ start_script_file }}"
    dest: "{{ pas_home }}/bin/start-PhenixID.sh"
    owner: "{{ user }}"

- name: "Add log configuration"
  copy:
    src: "{{ log4j2_config_file }}"
    dest: "{{ pas_home }}/config/log4j2.xml"
    owner: "{{ user }}"

- name: "Add license"
  copy:
    src: "{{ license_file }}"
    dest: "{{ pas_home }}/license/license.p12"
    owner: "{{ user }}"

- name: "Upload phenixid-pas service"
  template:
    src: pas.service.j2
    dest: "/lib/systemd/system/pas.service"
    mode: 644
  become: yes

