---

- name: "Remove directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pas_home }}/bin"
    - "{{ pas_home }}/lib"
    - "{{ pas_home }}/mods"
    - "{{ pas_home }}/repo"
    - "{{ pas_home }}/classes"
    - "{{ pas_home }}/config"
    - "{{ pas_home }}/resources"
  become: yes

- name: "Create install directory"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
    recurse: yes
  with_items:
    - "{{ pas_home }}"
    - "{{ pas_home }}/config"
    - "{{ pas_home }}/license"
  become: yes

- name: "Render install.varfile"
  template:
    src: install.varfile.j2
    dest: "{{ pas_home }}/install.varfile"
    mode: 0400
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes

- name: "Install from installer {{ pas_installer.local_path | basename }}"
  command: "{{ pas_installer.remote_path }}/{{ pas_installer.local_path | basename }} -q -varfile {{ pas_home }}/install.varfile"
  when: pas_installer.type == "installer"
  become: yes
  become_user: "{{ pas_service_user }}"

- name: "Set file and group ownership"
  file:
    path: "{{ pas_home }}"
    state: directory
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
    mode: "o-rwx"
    recurse: yes
  become: yes

- name: "Render sessions.xml"
  template:
    src: sessions.xml.j2
    dest: "{{ pas_home }}/config/sessions.xml"
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes

- name: "Render boot.json"
  template:
    src: boot.json.j2
    dest: "{{ pas_home }}/config/boot.json"
    mode: 0400
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes

- name: "Add start script"
  copy:
    src: "{{ pas_start_script }}"
    dest: "{{ pas_home }}/bin/start-PhenixID.sh"
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes
  when: pas_start_script is defined

- name: "Add log configuration"
  copy:
    src: "{{ pas_log4j2_config_file }}"
    dest: "{{ pas_home }}/config/log4j2.xml"
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes
  when: pas_log4j2_config_file is defined

- name: "Add license"
  copy:
    src: "{{ pas_license_file }}"
    dest: "{{ pas_home }}/license/license.p12"
    mode: 0400
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  become: yes
