---

pas_service_group: "{{ group }}"
pas_service_user: "{{ user }}"

signing_service_pas_user: "{{ pas_admin_user }}"
signing_service_pas_user_password: "{{ pas_admin_password }}"

digo_service_group: "{{ group }}"
digo_service_user: "{{ user }}"
digo_file_service_username: "{{ pas_admin_user }}"
digo_file_service_password: "{{ pas_admin_password }}"
digo_signing_service_url: "{{ signing_service_url }}"
digo_file_service_url: "{{ file_service_url }}"
digo_citizens_query_url: "{{ citizens_query_url }}"
digo_fob_query_url: "{{ fob_query_url }}"
digo_edu_query_url: "{{ edu_query_url }}"
digo_employees_query_url: "{{ employees_query_url }}"
digo_db_url: "{{ db_url }}"
