---

- include_role:
    name: phenixid.pas.pas_keystore

- include_role:
    name: phenixid.pas.pas_ca

- name: "Add samlidp"
  uri:
    method: PUT
    url: "{{ pas_config_api_url }}/config/samlidp"
    body: "{{ lookup('template', 'samlidp.json.j2') }}"
    body_format: json
