---


- name: "Add group {{ pas_service_group }}"
  group:
    name: "{{ pas_service_group }}"
    system: yes
    state: present
  become: yes

- name: "Add no-login system user {{ pas_service_user }}"
  user:
    name: "{{ pas_service_user }}"
    groups: "{{ pas_service_group }}"
    shell: /sbin/nologin
    append: no
    system: yes
    state: present
  become: yes

- name: "Upload {{ pas_installer.local_path }} to {{ pas_installer.remote_path }}"
  copy:
    src: "{{ pas_installer.local_path }}"
    dest: "{{ pas_installer.remote_path }}/"
    mode: 0500
    force: yes
    owner: "{{ pas_service_user }}"
    group: "{{ pas_service_group }}"
  when: digo_installer.remote_path is not undefined
  become: yes

- name: "Check service is installed"
  stat:
    path: "/etc/systemd/system/pas.service"
  register: service_stat

- name: "Stop service"
  systemd:
    state: stopped
    name: "pas"
  become: yes
  when: service_stat.stat.exists
  ignore_errors: yes

- name: "Install service file /etc/systemd/system/pas.service"
  template:
    src: "pas.service.j2"
    dest: "/etc/systemd/system/pas.service"
    mode: 0644
  become: yes

- include_role:
    name: phenixid.pas.pas

- name: "Service state: {{ pas_service_state }}"
  systemd:
    state: "{{ pas_service_state }}"
    daemon_reload: yes
    enabled: yes
    name: pas
  become: yes




